receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
processors:
  # Data sources: traces
  attributes:
    actions:
      - key: environment
        value: YOUR_COOL_COMPANY
        action: insert
  batch:
extensions:
  health_check: {}
exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true
  logging:
    loglevel: debug
    sampling_initial: 10
    sampling_thereafter: 1
  otlphttp:
    traces_endpoint: https://ingest.lightstep.com/traces/otlp/v0.9
    metrics_endpoint: https://ingest.lightstep.com/metrics/otlp/v0.9
    headers:
      "lightstep-access-token": XqyjLkWt76AtkzrwWr+Ja7JBXT9G4CvQVPGljqlCZrGvXeaozjnLPVSYz0CLKaltLA5oKJKaBahsTUnIuJRoqI6hrSNlJqKRz8zGA5x9
  otlp:
    endpoint: "ingest.lightstep.com:443"
    headers:
      "lightstep-access-token": XqyjLkWt76AtkzrwWr+Ja7JBXT9G4CvQVPGljqlCZrGvXeaozjnLPVSYz0CLKaltLA5oKJKaBahsTUnIuJRoqI6hrSNlJqKRz8zGA5x9
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [otlp, logging] 
    traces:
      receivers: [otlp]
      processors: [ batch, attributes]
      exporters: [otlp, logging, jaeger]

