receivers:
  otlp:
    protocols:
      grpc:
      http:
  # hostmetrics:
  #   scrapers:
  #     cpu:
  #     disk:
  #     filesystem:
  #     load:
  #     memory:
  #     network:
  #     process:
  #     processes:
processors:
  batch:
extensions:
  health_check: {}
exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true
  logging:
    loglevel: debug
    sampling_initial: 10
    sampling_thereafter: 1
  otlp:
    endpoint: "ingest.lightstep.com:443"
    headers:
      "lightstep-access-token": somelongtokenfromyoursettingspage
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [otlp, logging] 
    traces:
      receivers: [otlp]
      processors: [ batch]
      exporters: [otlp, logging, jaeger]

